apiVersion: v2
name: mlops-airflow
description: MLOps Airflow deployment using ArgoCD
type: application
version: 0.1.0
appVersion: "2.8.4"

dependencies:
  - name: airflow
    version: "8.9.0"
    repository: https://airflow-helm.github.io/charts
  - name: postgresql
    version: 8.6.4
    repository: https://charts.helm.sh/stable
    condition: postgresql.enabled
  - name: redis
    version: 10.5.7
    repository: https://charts.helm.sh/stable
    condition: redis.enabled
